# Generated by Django 3.2.20 on 2023-09-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230909_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(),
            preserve_default=False,
        ),
    ]
